steps:
  build-and-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: "${CI_REPO_OWNER##mu-}/mu-${CI_REPO_NAME}"
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
when:
  - event: push
    branch: [master]
