pipeline:
  build-and-push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    settings:
      repo: "${CI_REPO_OWNER##mu-}/mu-${CI_REPO_NAME}"
      tags: ${CI_REPO_TAG##v}
    when:
      event: tag
      tag: v*
branches:
  - master
